# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "64b50aa7971e5f157ad668b4f902b93b"
name = "Custom Form Builder"
application_url = "https://app-applications.myshopify.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_files,write_products,read_themes"

[auth]
redirect_urls = []

[app_proxy]
url = "/apps/custom-form-builder"
subpath = "submit"
prefix = "apps"
